dist: precise

addons:
  mariadb: '10.0'

language: ruby
rvm:
  - 2.4

before_script:
  - mysql -e 'create database mysql_online_migrations;'

gemfile:
  - gemfiles/rails4_2.gemfile

script: bundle exec rspec spec
