dist: trusty

services:
  - mysql

language: ruby
rvm:
  - 2.5
  - 2.6

before_script:
  - mysql -e 'create database mysql_online_migrations;'

gemfile:
  - gemfiles/rails6_0.gemfile

script: bundle exec rspec spec
